/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perez_program;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
public class CAFETERIA extends javax.swing.JFrame {

    /**
     * Creates new form CAFETERIA
     */
    public CAFETERIA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        txtPRODUCT = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTOTALPRICE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtQUANTITY = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCHANGE = new javax.swing.JTextField();
        btnTOTAL = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtAMOUNT = new javax.swing.JTextField();
        chk_cupcake = new javax.swing.JCheckBox();
        cake = new javax.swing.JCheckBox();
        bentocake = new javax.swing.JCheckBox();
        strawberry = new javax.swing.JCheckBox();
        mango = new javax.swing.JCheckBox();
        blueberry = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPRODUCT.setBackground(new java.awt.Color(204, 204, 255));
        txtPRODUCT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setText("MENU");
        txtPRODUCT.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("SNACKS");
        txtPRODUCT.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("DRINKS");
        txtPRODUCT.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("CHANGE  :");
        txtPRODUCT.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        txtTOTALPRICE.setForeground(new java.awt.Color(255, 255, 255));
        txtTOTALPRICE.setEnabled(false);
        txtPRODUCT.add(txtTOTALPRICE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 230, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("QUANTITY :");
        txtPRODUCT.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));
        txtPRODUCT.add(txtQUANTITY, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 230, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("TOTAL PRICE : ");
        txtPRODUCT.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));
        txtPRODUCT.add(txtCHANGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 230, -1));

        btnTOTAL.setBackground(new java.awt.Color(204, 0, 0));
        btnTOTAL.setText("TOTAL");
        btnTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTOTALActionPerformed(evt);
            }
        });
        txtPRODUCT.add(btnTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 130, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("ENTER AMOUNT : ");
        txtPRODUCT.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));
        txtPRODUCT.add(txtAMOUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 230, -1));

        chk_cupcake.setText("Cupcake ₱50");
        txtPRODUCT.add(chk_cupcake, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        cake.setText("Cake ₱250");
        txtPRODUCT.add(cake, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        bentocake.setText("BentoCake ₱200");
        txtPRODUCT.add(bentocake, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        strawberry.setText("Strawberry shake ₱150");
        txtPRODUCT.add(strawberry, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        mango.setText("Mango Shake ₱150");
        txtPRODUCT.add(mango, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        blueberry.setText("BlueBerry Shake ₱150");
        txtPRODUCT.add(blueberry, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        txtPRODUCT.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, -1, -1));

        getContentPane().add(txtPRODUCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTOTALActionPerformed
        des();
        
    }//GEN-LAST:event_btnTOTALActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        des();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void des(){
           int product = Integer.parseInt(txtQUANTITY.getText());
        int totprice = Integer.parseInt(txtTOTALPRICE.getText());
        int amount  = Integer.parseInt(txtAMOUNT.getText());
        int change = Integer.parseInt(txtCHANGE.getText());
        int total;
        int price = 0;
        
        
        if(chk_cupcake.isSelected()){
            price += 50;
        } 
        if(cake.isSelected()){
            price += 250;
        } 
        if(bentocake.isSelected()){
            price += 200;
        } 
        if(strawberry.isSelected()){
            price += 150; 
        }
        if(mango.isSelected()){
            price += 150;
        } 
        if(blueberry.isSelected()){
            price += 150;
        }
        
        total = price * product;
        
        
        change = amount - total;
        txtTOTALPRICE.setText("" + total);
        
        if (amount < total){
            
            JOptionPane.showMessageDialog(rootPane, "INSUFFICIENT BALANCE ","RECEIPT", JOptionPane.INFORMATION_MESSAGE);
            txtAMOUNT.setText("");
            txtTOTALPRICE.setText("");
        }

            txtCHANGE.setText("" + change);
        
     
        
    
    
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAFETERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAFETERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAFETERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAFETERIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAFETERIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bentocake;
    private javax.swing.JCheckBox blueberry;
    private javax.swing.JButton btnTOTAL;
    private javax.swing.JCheckBox cake;
    private javax.swing.JCheckBox chk_cupcake;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JCheckBox mango;
    private javax.swing.JCheckBox strawberry;
    private javax.swing.JTextField txtAMOUNT;
    private javax.swing.JTextField txtCHANGE;
    private javax.swing.JPanel txtPRODUCT;
    private javax.swing.JTextField txtQUANTITY;
    private javax.swing.JTextField txtTOTALPRICE;
    // End of variables declaration//GEN-END:variables
}
