/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perez_program;

import javax.swing.JOptionPane;

/**
 *
 * @author CL2-PC
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_quan = new javax.swing.JTextField();
        txt_change = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_cash = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_totalamount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        chck_strawberryshake = new javax.swing.JCheckBox();
        chck_blueberryshake = new javax.swing.JCheckBox();
        chck_mangoshake = new javax.swing.JCheckBox();
        chck_piatos = new javax.swing.JCheckBox();
        chck_chichirya = new javax.swing.JCheckBox();
        chck_cupcake = new javax.swing.JCheckBox();

        jLabel3.setText("jLabel3");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel8.setText("CAFETERIA MENU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 80));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("SNACKS ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 210, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("DRINKS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 51, 255));
        jPanel2.setForeground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 170, 50));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("CREATE ANOTHER ORDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        txt_quan.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jPanel2.add(txt_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 230, 30));

        txt_change.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jPanel2.add(txt_change, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 230, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setText("Change : ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        txt_cash.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jPanel2.add(txt_cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 230, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setText("Amount : ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        txt_totalamount.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jPanel2.add(txt_totalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 230, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("Total :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Quantity :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        chck_strawberryshake.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        chck_strawberryshake.setText("STRAWBERRY SHAKE - 190");
        jPanel2.add(chck_strawberryshake, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, 30));

        chck_blueberryshake.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        chck_blueberryshake.setText("BLUEBERRY SHAKE  - 120");
        jPanel2.add(chck_blueberryshake, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, 30));

        chck_mangoshake.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        chck_mangoshake.setText("MANGO SHAKE - 106");
        jPanel2.add(chck_mangoshake, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, 30));

        chck_piatos.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        chck_piatos.setText("Piatos - 30");
        jPanel2.add(chck_piatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 200, 40));

        chck_chichirya.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        chck_chichirya.setText("Chichirya - 25");
        jPanel2.add(chck_chichirya, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 180, 40));

        chck_cupcake.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        chck_cupcake.setText("Cupcake  - 20");
        jPanel2.add(chck_cupcake, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 170, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 670, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int quan = Integer.parseInt(txt_quan.getText());
        int cash = Integer.parseInt(txt_cash.getText());
        int change = 0;
        int total = 0;
        int price = 0;
        
        if(chck_cupcake.isSelected()){
            price += 20;
        }
         if(chck_chichirya.isSelected()){
            price += 25;
        }
          if(chck_piatos.isSelected()){
            price += 30;
        }
        
          if(chck_mangoshake.isSelected()){
              price += 109;
          }
          if(chck_blueberryshake.isSelected()){
              price +=120;
          }
          if (chck_strawberryshake.isSelected()){
              price +=190;
          }
          
          total = price * quan;
          change = cash - total;
          txt_totalamount.setText("" + total);
          
          
          if (total > cash ){
              JOptionPane.showMessageDialog(rootPane, "INSUFFICIENT BALANCE", "RECEIPT",JOptionPane.INFORMATION_MESSAGE);
              txt_totalamount.setText("");
              txt_cash.setText("");
              
          }
          txt_change.setText("" + change);
          
          
          
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        chck_cupcake.setSelected(false);
        chck_chichirya.setSelected(false);
        chck_piatos.setSelected(false);
        chck_mangoshake.setSelected(false);
        chck_blueberryshake.setSelected(false);
        chck_strawberryshake.setSelected(false);
        txt_quan.setText("");
        txt_totalamount.setText("");
        txt_cash.setText("");
        txt_change.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chck_blueberryshake;
    private javax.swing.JCheckBox chck_chichirya;
    private javax.swing.JCheckBox chck_cupcake;
    private javax.swing.JCheckBox chck_mangoshake;
    private javax.swing.JCheckBox chck_piatos;
    private javax.swing.JCheckBox chck_strawberryshake;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_cash;
    private javax.swing.JTextField txt_change;
    private javax.swing.JTextField txt_quan;
    private javax.swing.JTextField txt_totalamount;
    // End of variables declaration//GEN-END:variables
}
