/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perez_program;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class NewJFrame1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame1.class.getName());

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 170, -1));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 170, -1));

        jLabel1.setText("PLAYER 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jLabel2.setText("PLAYER 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel3.setText("[1] ROCK");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 90, 30));

        jLabel4.setText("[2] PAPER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabel5.setText("[3] SCISSOR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, 20));

        jButton1.setText("VS");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int p1 = Integer.parseInt(txt1.getText());
        int p2 = Integer.parseInt(txt2.getText());
        
        if (p1 == 1 && p2 == 1)
        {
            JOptionPane.showMessageDialog(rootPane,"Draw","RPS",JOptionPane.INFORMATION_MESSAGE);
        }
         else if (p1 == 1 && p2 == 2)
        {
           JOptionPane.showMessageDialog(rootPane,"PLAYER 2 WINS","RPS",JOptionPane.INFORMATION_MESSAGE);
            
        }
        
        else if (p1 == 1 && p2 == 3)
        {
            JOptionPane.showMessageDialog(rootPane,"PLAYER 1 WINS","RPS",JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if (p1 == 2 && p2 == 2)
        {
            JOptionPane.showMessageDialog(rootPane,"Draw","RPS",JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if (p1 == 2 && p2 == 1)
        {
            JOptionPane.showMessageDialog(rootPane,"PLAYER 1 WINS","RPS",JOptionPane.INFORMATION_MESSAGE);
            
        }
        else if (p1 == 2 && p2 == 3)
        {
           JOptionPane.showMessageDialog(rootPane,"PLAYER 2 WINS","RPS",JOptionPane.INFORMATION_MESSAGE);
            
        }
           else if (p1 == 3 && p2 == 3)
        {
           JOptionPane.showMessageDialog(rootPane,"Draw","RPS",JOptionPane.INFORMATION_MESSAGE);
            
        }
           else if (p1 == 3 && p2 == 1)
        {
            JOptionPane.showMessageDialog(rootPane,"PLAYER 1 WINS ","RPS",JOptionPane.INFORMATION_MESSAGE);
            
        }
         else if (p1 == 3 && p2 == 2)
        {
          JOptionPane.showMessageDialog(rootPane,"PLAYER 2 WINSS","RPS",JOptionPane.INFORMATION_MESSAGE);
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
